
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upbpqcpeyomerhvqdmbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwYnBxY3BleW9tZXJodnFkbWJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMjA0NjcsImV4cCI6MjA2MDc5NjQ2N30.yE6phtYJUWkhNT1R5F3VnzQy2bUNRhajO6yJAR8OEmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
